import { test, expect, type APIRequestContext, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import sharp from 'sharp';
import { PAPER } from '../scripts/lib/design.mjs';

/**
 * Guards the properties that make this site cheap to load. These are easy to
 * regress silently — one `client:load` directive would ship a React runtime
 * to a page that is otherwise pure text.
 */

// The stylesheet is around 15 KB uncompressed. 20 KB leaves room for a few
// more utilities without leaving room for a regression: at the old 30 KB the
// budget had nearly 2x headroom and would not have caught anything.
const CSS_BUDGET_BYTES = 20 * 1024;

/** Every route that ships to users. Link and analytics rules apply to all. */
const ROUTES = ['/', '/about'];

/**
 * Every stylesheet on the page, inline or linked, as source text.
 *
 * The build inlines its CSS, so a check that only followed
 * `link[rel="stylesheet"]` would find nothing and pass against zero bytes —
 * silently, and exactly when it was most worth checking. Both forms are
 * collected so these hold whichever way the CSS ships.
 */
async function stylesheets(page: Page, request: APIRequestContext): Promise<string[]> {
  const inline = await page
    .locator('style')
    .evaluateAll((nodes) => nodes.map((node) => node.textContent ?? ''));

  const hrefs = await page
    .locator('link[rel="stylesheet"]')
    .evaluateAll((nodes) => nodes.map((node) => (node as HTMLLinkElement).href));

  const linked = await Promise.all(hrefs.map(async (href) => (await request.get(href)).text()));

  const all = [...inline, ...linked];
  expect(all.join(''), 'no CSS found on the page at all').not.toHaveLength(0);
  return all;
}

test('ships no framework JavaScript', async ({ page }) => {
  const scripts: string[] = [];
  page.on('request', (request) => {
    if (request.resourceType() === 'script') scripts.push(request.url());
  });

  await page.goto('/', { waitUntil: 'networkidle' });

  // Inline scripts (theme resolver, toggle) do not issue requests. Anything
  // fetched here is a bundle, which this page should never need.
  expect(scripts, `unexpected script requests: ${scripts.join(', ')}`).toHaveLength(0);
});

test('keeps CSS within budget', async ({ page, request }) => {
  await page.goto('/');

  const total = (await stylesheets(page, request)).reduce(
    (bytes, css) => bytes + Buffer.byteLength(css),
    0,
  );

  expect(total, `stylesheets total ${total} bytes uncompressed`).toBeLessThan(CSS_BUDGET_BYTES);
});

for (const route of ROUTES) {
  test(`gives every tracked link on ${route} a unique, valid Umami event name`, async ({
    page,
  }) => {
    await page.goto(route);

    const events = await page
      .locator('[data-umami-event]')
      .evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-umami-event')!));

    expect(events.length).toBeGreaterThan(0);
    // Umami caps event names at 50 characters.
    for (const event of events) expect(event.length).toBeLessThanOrEqual(50);
    // Sharing a name across links would merge two placements into one statistic.
    expect(new Set(events).size, `duplicate event names: ${events.join(', ')}`).toBe(events.length);
  });
}

// The same destination appears on both routes (LinkedIn as a profile on the
// home card, as "Projects" in the About footer). Reusing one event name would
// make it impossible to tell which placement a reader actually used.
test('does not reuse an event name across routes', async ({ page }) => {
  const seen = new Map<string, string>();

  for (const route of ROUTES) {
    await page.goto(route);
    const events = await page
      .locator('[data-umami-event]')
      .evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-umami-event')!));

    for (const event of events) {
      expect(seen.get(event), `"${event}" is used on both ${seen.get(event)} and ${route}`)
        .toBeUndefined();
      seen.set(event, route);
    }
  }
});

test('omits the tracker when no website ID is configured', async ({ request }) => {
  // The test build runs without PUBLIC_UMAMI_WEBSITE_ID, standing in for a
  // local development build — which must never report traffic.
  const html = await (await request.get('/')).text();
  expect(html).not.toContain('cloud.umami.is');
});

for (const route of ROUTES) {
  test(`opens outbound links on ${route} safely`, async ({ page }) => {
    await page.goto(route);

    const links = page.locator('a[href^="http"]');
    const count = await links.count();
    expect(count).toBeGreaterThan(0);

    for (let i = 0; i < count; i++) {
      const rel = await links.nth(i).getAttribute('rel');
      expect(rel, `link ${i} is missing rel`).toContain('noopener');
      expect(rel).toContain('noreferrer');
    }
  });
}

// Regenerated by `npm run generate:favicon`; pinned so a moved or renamed
// output fails loudly instead of 404ing only in a browser tab.
test('serves the icon set and links it from the head', async ({ page, request }) => {
  await page.goto('/');

  await expect(page.locator('link[rel="icon"]')).toHaveAttribute('href', '/favicon.ico');
  await expect(page.locator('link[rel="apple-touch-icon"]')).toHaveAttribute(
    'href',
    '/apple-touch-icon.png',
  );
  expect((await request.get('/favicon.ico')).status()).toBe(200);
  expect((await request.get('/apple-touch-icon.png')).status()).toBe(200);
});

/**
 * The page surface is written down in three places that cannot read each
 * other: `--background` in global.css, the `theme-color` metas (which predate
 * oklch), and `PAPER` in scripts/lib/design.mjs (Node cannot read the
 * stylesheet). Comments say to keep them in sync; this makes drift fail.
 *
 * The stylesheet is the authority, so the check samples what the browser
 * actually paints rather than re-deriving the conversion — sampling at the
 * top-left corner, the toggle being fixed to the right and the card centred.
 *
 * Each theme is sampled on a fresh load. Switching schemes on a live page
 * would sample mid-fade, since the body carries a 260ms background
 * transition; on load the head resolver has already settled the theme.
 */
async function paintedBackground(page: Page): Promise<string> {
  const shot = await page.screenshot({ clip: { x: 0, y: 0, width: 1, height: 1 } });
  const { data } = await sharp(shot).raw().toBuffer({ resolveWithObject: true });
  return `#${[...data.subarray(0, 3)].map((c) => c.toString(16).padStart(2, '0')).join('')}`;
}

test('keeps the hand-written surface colours matching the stylesheet', async ({
  page,
}) => {
  await page.emulateMedia({ colorScheme: 'light' });
  await page.goto('/');

  const light = await paintedBackground(page);
  expect(light, 'PAPER in scripts/lib/design.mjs no longer matches --background').toBe(
    PAPER,
  );
  await expect(
    page.locator('meta[name="theme-color"][media*="light"]'),
  ).toHaveAttribute('content', light);

  // Dark has no generator constant — nothing draws on it — so this half pins
  // the meta alone.
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.goto('/');

  const dark = await paintedBackground(page);
  expect(dark, 'light and dark resolved to the same colour').not.toBe(light);
  await expect(page.locator('meta[name="theme-color"][media*="dark"]')).toHaveAttribute(
    'content',
    dark,
  );
});

// The font is the whole visual identity here, so a late or unhinted download
// is a visibly unstyled page. Guards the preload hint and the `swap` policy.
test('preloads the latin font subset', async ({ page, request }) => {
  await page.goto('/');

  const preload = page.locator('link[rel="preload"][as="font"]');
  await expect(preload).toHaveCount(1);

  const href = await preload.getAttribute('href');
  expect(href).toMatch(/newsreader-latin-.*\.woff2$/);
  expect((await request.get(href!)).status()).toBe(200);

  const sheets = await stylesheets(page, request);
  // Matched loosely because the built CSS is minified (`font-display:swap`).
  expect(sheets.join('')).toMatch(/font-display:\s*swap/);
});

// `swap` only stops being a visible flicker if the fallback occupies exactly
// the space the real font will. This asserts the metric overrides in
// `global.css` still hold: with the woff2 blocked, nothing on the page may sit
// anywhere other than where it lands once Newsreader has loaded.
//
// The failure this catches is not subtle when it happens — before the
// overrides, the opening bio paragraph wrapped to four lines in Georgia where
// Newsreader takes three, dropping everything below it by 34px. It is subtle
// to notice, because it only appears in the few hundred milliseconds before
// the font arrives.
//
// Host-font dependent: the overrides only engage where one of the calibrated
// faces is installed — Georgia or Times New Roman on macOS and Windows, or
// the Liberation/Noto/DejaVu rules on Linux. deploy.yml's test job installs
// fonts-liberation and fonts-dejavu-core precisely so the blocked pass has a
// calibrated fallback to land on; on a machine with none of these, the test
// falls through to a generic serif and fails honestly.
for (const route of ROUTES) {
  for (const width of [390, 1280]) {
    test(`swaps ${route} into Newsreader without reflowing at ${width}px`, async ({ page }) => {
      await page.setViewportSize({ width, height: 900 });

      const positions = async (blocked: boolean) => {
        // `intercepted`, not `route` — the loop's route is the page path.
        if (blocked) await page.route('**/*.woff2', (intercepted) => intercepted.abort());
        else await page.unroute('**/*.woff2');

        await page.goto(route);
        if (!blocked) await page.evaluate(() => document.fonts.ready);

        return page.evaluate(() =>
          [...document.querySelectorAll('h1, p, nav a, span')].map((el) => {
            const box = el.getBoundingClientRect();
            return { top: box.top, height: box.height };
          }),
        );
      };

      const fallback = await positions(true);
      const loaded = await positions(false);

      expect(fallback.length).toBeGreaterThan(0);
      expect(fallback).toHaveLength(loaded.length);

      // Sub-pixel tolerance only: a whole line is ~34px, so anything real
      // fails this by two orders of magnitude.
      for (const [i, box] of loaded.entries()) {
        expect(Math.abs(box.top - fallback[i].top), `element ${i} moved on swap`).toBeLessThan(0.5);
        expect(
          Math.abs(box.height - fallback[i].height),
          `element ${i} changed height on swap`,
        ).toBeLessThan(0.5);
      }
    });
  }
}

// The font carries only the characters src/content/site.ts needed when
// `npm run generate:font` last ran. Adding a character to the copy without
// regenerating would render it from a system serif — one glyph mid-word in
// the wrong face, which is easy to miss in review and impossible to miss on
// the page. This turns that into a failing test naming the character.
//
// The arrows are the documented exception: U+2190/2192/2197 are in none of
// Newsreader's upstream subsets either, so they have always come from a
// system font and are not something subsetting took away.
const SYSTEM_RENDERED = new Set(['←', '→', '↗']);

// The subset narrows Newsreader's wght and opsz axes to the ranges in
// scripts/generate-font.mjs, so the build may not emit a weight or size
// outside them — the browser would ask the font for a variation it no longer
// carries, and get the nearest pinned instance instead: semibold at 600 is
// fine, but a 700 or a 48px name would silently come out wrong. The bounds
// come from the manifest the generator writes (the way the glyph-coverage
// test below reads its codepoints), so widening them stays a one-file change
// plus a regenerate, and a failure here always names the range actually
// subset. The check runs against the emitted CSS rather than the templates
// because that is what the browser matches against.
//
// Scoped to px: named text utilities would emit rem, which this does not
// resolve. The design sizes everything in `text-[Npx]`, so nothing is missed
// today; a named utility sneaking in weakens the guard rather than failing
// it, which is worth knowing before reaching for one.
test('keeps every emitted weight and size inside the subset', async ({ page, request }) => {
  await page.goto('/');

  const css = (await stylesheets(page, request)).join('');

  const { weight: wght, opticalSize: opsz } = JSON.parse(
    await readFile('src/assets/newsreader-latin-subset.json', 'utf8'),
  );

  const weights = [...css.matchAll(/font-weight:\s*(\d+)/g)].map((m) => Number(m[1]));
  const sizes = [...css.matchAll(/font-size:\s*(\d+(?:\.\d+)?)px/g)].map((m) => Number(m[1]));

  expect(weights.length, 'no font-weight declarations found at all').toBeGreaterThan(0);
  expect(sizes.length, 'no px font-size declarations found at all').toBeGreaterThan(0);

  for (const weight of weights) {
    expect(
      weight,
      `font-weight ${weight} is outside the subset's wght ${wght.min}-${wght.max}`,
    ).toBeGreaterThanOrEqual(wght.min);
    expect(
      weight,
      `font-weight ${weight} is outside the subset's wght ${wght.min}-${wght.max}`,
    ).toBeLessThanOrEqual(wght.max);
  }

  for (const size of sizes) {
    expect(
      size,
      `font-size ${size}px is outside the subset's opsz ${opsz.min}-${opsz.max}`,
    ).toBeGreaterThanOrEqual(opsz.min);
    expect(
      size,
      `font-size ${size}px is outside the subset's opsz ${opsz.min}-${opsz.max}`,
    ).toBeLessThanOrEqual(opsz.max);
  }
});

for (const route of ROUTES) {
  test(`renders ${route} entirely from the subset font`, async ({ page }) => {
    await page.goto(route);

    const rendered: string[] = await page.evaluate(() => {
      const body = document.body.cloneNode(true) as HTMLElement;
      body.querySelectorAll('script, style').forEach((node) => node.remove());
      return [...new Set(body.textContent ?? '')];
    });

    const { codepoints } = JSON.parse(
      await readFile('src/assets/newsreader-latin-subset.json', 'utf8'),
    );
    const covered = new Set((codepoints as number[]).map((c) => String.fromCodePoint(c)));

    const missing = rendered.filter(
      (char) => !covered.has(char) && !SYSTEM_RENDERED.has(char) && !/\s/.test(char),
    );

    expect(
      missing,
      `not in the subset — run \`npm run generate:font\`: ${missing.map((c) => `${c} (U+${c.codePointAt(0)!.toString(16).toUpperCase().padStart(4, '0')})`).join(', ')}`,
    ).toHaveLength(0);
  });
}
