/**
 * All page copy lives here so text can be edited without touching layout.
 *
 * A content collection would be overkill for two pages — this is a plain typed
 * module, and TypeScript fails the build if an entry is malformed.
 */

export interface Link {
  /**
   * The visible label, and the link's accessible name. Kept short — these sit
   * in a tight row.
   */
  text: string;
  href: string;
  /**
   * `↗` marks a link that leaves the site, `→` one that continues within the
   * same reading. Carried from the design, where the two are used distinctly.
   * Rendered `aria-hidden` — it is decoration, not part of the name.
   */
  glyph: '↗' | '→';
  /** Umami event name. Keep stable — renaming fragments historical data. */
  event: string;
  /**
   * Adds `rel="me"` alongside the usual hardening. Marks the destination as
   * the same person's profile — the bidirectional signal identity
   * verification (Mastodon, IndieWeb) looks for. Only for profile roots.
   */
  relMe?: boolean;
}

export interface BioParagraph {
  /**
   * Optional bold lead-in, rendered inline before the text — the design uses
   * it once, for "Now." Written separately rather than as inline markup so
   * the copy stays plain strings and needs no HTML escaping.
   */
  lead?: string;
  text: string;
}

/** One row of a `LabeledRows` section — the tech stack and the interests. */
export interface LabeledRow {
  /** Left column. Recedes behind the value it labels. */
  label: string;
  /** Right column. Free-form, comma-separated. */
  value: string;
}

export interface SiteContent {
  name: string;
  /** The single line under the name on the home card. Keep it to one line. */
  identity: string;
  /**
   * Search-snippet descriptions, one per route. Written for the snippet, not
   * reused from page copy: 50–160 characters, with the terms a searcher
   * would type. Keep them truthful — Google rewrites snippets that oversell.
   */
  homeDescription: string;
  aboutDescription: string;
  bio: BioParagraph[];
  /** Feeds `knowsAbout` in the structured data as well as the About page. */
  stack: LabeledRow[];
  interests: LabeledRow[];
  /** Rendered as text links on the home card, and used as `sameAs`. */
  profiles: Link[];
  /** Rendered in the About page footer. */
  aboutLinks: Link[];
  /** Used as `jobTitle` in the Person structured data. */
  jobTitle: string;
  /**
   * Share-card image, site-root-relative. Served from `public/` rather than
   * astro:assets on purpose: crawlers and social scrapers need a stable URL,
   * and processed assets carry a content hash that changes between builds.
   *
   * The 1200x630 card is generated by `npm run generate:og`; the dimensions
   * and alt text below are emitted as og:image metadata and must stay in
   * step with it.
   */
  ogImage: string;
  ogImageWidth: number;
  ogImageHeight: number;
  ogImageAlt: string;
  /**
   * Square portrait used as `image` in the Person structured data. Kept
   * separate from the share card: schema.org expects a photo of the person,
   * not a designed card with text.
   */
  personImage: string;
  /** Carried over from the previous site — removing it breaks Search Console. */
  googleSiteVerification: string;
}

export const site: SiteContent = {
  name: 'Koushik',

  identity: 'I design systems and build teams that ship',

  homeDescription:
    'Koushik — software engineer designing platforms, distributed systems, and building teams that ship.',

  aboutDescription:
    'About Koushik — software engineer designing platforms, distributed systems, and building teams that ship.',

  bio: [
    {
      text: 'I’ve spent over a decade designing systems and building software. Five years at a B2C startup as the founding engineer, then six at a B2B SaaS company — where I built the team from scratch and own what it ships, now past 450 customers.',
    },
    {
      lead: 'Now.',
      text: 'Building workflow platforms where a person and an agent are the same kind of user.',
    },
  ],

  stack: [
    { label: 'Languages', value: 'TypeScript' },
    { label: 'Technologies', value: 'Node.js, React' },
    { label: 'Databases', value: 'MongoDB, PostgreSQL' },
    { label: 'DevOps & infra', value: 'AWS, Docker' },
  ],

  interests: [
    { label: 'Learning', value: 'Functional programming with OCaml' },
    { label: 'Training', value: 'Kettlebells' },
    { label: 'Seasonal', value: 'Swimming, Running, Motorcycle touring, Hiking' },
  ],

  // These two are the `sameAs` set in the structured data, so they must be
  // exactly the outbound links rendered on the home page — structured data
  // that disagrees with the page it describes is worse than none at all.
  profiles: [
    {
      text: 'LinkedIn',
      href: 'https://www.linkedin.com/in/srikoushik/',
      glyph: '↗',
      event: 'outbound-linkedin',
      relMe: true,
    },
    {
      text: 'GitHub',
      href: 'https://github.com/srikoushik',
      glyph: '↗',
      event: 'outbound-github',
      relMe: true,
    },
  ],

  // Deeper destinations, surfaced only once a reader has opened About. Their
  // event names are distinct from the home card's so the two placements stay
  // separable in the analytics.
  aboutLinks: [
    {
      text: 'Projects',
      href: 'https://www.linkedin.com/in/srikoushik/details/projects/',
      glyph: '↗',
      event: 'about-outbound-projects',
    },
    {
      text: 'Blog',
      href: 'https://medium.com/@srikoushik',
      glyph: '↗',
      event: 'about-outbound-blog',
    },
  ],

  jobTitle: 'Software Engineer',

  ogImage: '/og-card.jpg',
  ogImageWidth: 1200,
  ogImageHeight: 630,
  ogImageAlt: 'Koushik — I design systems and build teams that ship',

  personImage: '/me.jpg',

  googleSiteVerification: '3E6n8pS7eidjtwTD4pma59fyB7674Hw6Eez5r-HLDIU',
};
